version: '3.8'

services:
  backend:
    container_name: dwh-client-tool-backend
    build: ./src/backend
    command: |
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn api.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - ./src/backend:/usr/src/backend/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://<benutzer>:<passwort>@<host>:<port>/<datenbankname>
      